# Generated by Django 5.2.3 on 2025-06-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_media_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_covers/'),
        ),
    ]
